[package]
name = "podcastindex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest="0.11.9"
sha1="0.10.0"
urlencoding = "2.1.0"
tokio = { version = "1", features = ["full"] }
